# Generated by Django 6.0 on 2026-01-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description_text', models.TextField(blank=True)),
                ('description_file', models.FileField(blank=True, null=True, upload_to='job_descriptions/')),
                ('processed_text', models.TextField(blank=True)),
                ('gliner_entities', models.JSONField(blank=True, null=True)),
                ('jina_embedding', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
